dist: xenial
language: scala
services:
  - docker

jdk:
  - openjdk8
  - openjdk11

env:
- SCALA_VERSION=2.13.1
- SCALA_VERSION=2.12.10
- SCALA_VERSION=2.11.12
- SCALA_VERSION=2.13.1 PAHO_CLIENT_VERSION=1.2.0
- SCALA_VERSION=2.13.1 PAHO_CLIENT_VERSION=1.2.2

script:
  - sbt ++$SCALA_VERSION test

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
